version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "apanicker-nflx"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
